/* eslint-disable import/prefer-default-export */
export const quiz = {
  questions: [
    {
      question: 'Which of these is NOT a 3rd generation Cephalosporin?',
      answerSelectionType: 'single',
      answers: [
        'Cefditoren',
        'Cefprozil',
        'Cefdinir',
        'Cefpodoxime',
      ],
      correctAnswer: '2',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'What is the flavor of Orelox suspension?',
      answerSelectionType: 'single',
      answers: [
        'Banana flavor',
        'Vanilla flavor',
        'Strawberry flavor',
        'Coconut flavor',
      ],
      correctAnswer: '1',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'Which of these do you need an antibiotic to treat?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Viral infection',
        'Herpes simplex',
        'Mouth sores',
        'Streptococcal throat infection',
      ],
      correctAnswer: '4',
      point: '10',
    },
    {
      question: 'The Centor scoring system is used to classify and suggest management of which of these?',
      answerSelectionType: 'single',
      answers: [
        'Bronchitis',
        'Staph tonsillopharyngitis',
        'Streptococcal tonsillopharyngitis',
        'Cough',
      ],
      correctAnswer: '3',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'How often is Orelox to be taken?',
      answerSelectionType: 'single',
      answers: [
        'Once-daily',
        'Twice daily',
        'Three times daily',
        'Not given',
      ],
      correctAnswer: '2',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'Fewer antibiotics have been created in the last 30 years',
      answerSelectionType: 'single',
      answers: [
        'True',
        'False',
      ],
      correctAnswer: '1',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'The dose for use of Orelox in tonsilitis for adults is 100mg b.d for 5 days',
      answerSelectionType: 'single',
      answers: [
        'True',
        'False',
      ],
      correctAnswer: '1',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'The first-generation cephalosporins are solely active against gram-positive organisms',
      answerSelectionType: 'single',
      answers: [
        'True',
        'False',
      ],
      correctAnswer: '1',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'The second-generation has improved activity against gram-negative and some anaerobes but less activity against gram-positive microbes',
      answerSelectionType: 'single',
      answers: [
        'True',
        'False',
      ],
      correctAnswer: '1',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'The third-generation cephalosporins are broad-spectrum antimicrobial agents with activity against both gram-negative and gram-positive organisms',
      answerSelectionType: 'single',
      answers: [
        'True',
        'False',
      ],
      correctAnswer: '1',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'The third generation cephalosporins are more active against gram-negative bacteria and organisms that are resistant to the first and second regeneration cephalosporins',
      answerSelectionType: 'single',
      answers: [
        'True',
        'False',
      ],
      correctAnswer: '1',
      point: '10',
      questionType: 'text',
    },
    {
      question: 'Third-generation cephalosporins show more stability to beta-lactamases than first or second generations, especially those produced by Klebsiella, Haemophilus infuenzae, and Escherichia coli',
      answerSelectionType: 'single',
      answers: [
        'True',
        'False',
      ],
      correctAnswer: '1',
      point: '10',
      questionType: 'text',
    },

  ],
  quizTitle: 'What\'s your React iQ?',
  // quizSynopsis: 'Tap below to get started',
  appLocale: {
    landingHeaderText: 'Find out in <questionLength> quick questions',
    question: '',
    startQuizBtn: 'Begin',
    resultFilterAll: 'All',
    resultFilterCorrect: 'Correct',
    resultFilterIncorrect: 'Incorrect',
    nextQuestionBtn: 'Next',
    resultPageHeaderText: 'You have completed the quiz. You got <correctIndexLength> out of <questionLength> questions.',
    resultPagePoint: 'You scored <correctPoints>%',
  },
};
